[wokwi]
version = 1
firmware = '.pio/build/esp32dev/firmware.bin'
elf = '.pio/build/esp32dev/firmware.elf'

serialMonitor = { display = "always" }

rfc2217ServerPort = 5000

[meta]
projectType = "platformio"

